package fr.polytech.polydiploma.remote.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-03-29T16:18:13.301+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", name = "OrganisationWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrganisationWebService {

    @WebMethod
    @RequestWrapper(localName = "addSpeaker", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.AddSpeaker")
    @ResponseWrapper(localName = "addSpeakerResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.AddSpeakerResponse")
    public void addSpeaker(
        @WebParam(name = "speaker", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Speaker speaker,
        @WebParam(name = "timeslot", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Timeslot timeslot
    ) throws ExternalPartnerException_Exception, TimeslotOverlapException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getDeliveryDate", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetDeliveryDate")
    @ResponseWrapper(localName = "getDeliveryDateResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetDeliveryDateResponse")
    @WebResult(name = "delivery_date", targetNamespace = "")
    public fr.polytech.polydiploma.remote.stubs.Date getDeliveryDate() throws ExternalPartnerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getParticipantList", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetParticipantList")
    @ResponseWrapper(localName = "getParticipantListResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetParticipantListResponse")
    @WebResult(name = "participant_list", targetNamespace = "")
    public java.util.List<fr.polytech.polydiploma.remote.stubs.Participant> getParticipantList();

    @WebMethod
    @RequestWrapper(localName = "addGraduate", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.AddGraduate")
    @ResponseWrapper(localName = "addGraduateResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.AddGraduateResponse")
    public void addGraduate(
        @WebParam(name = "graduate", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Graduate graduate
    ) throws ExternalPartnerException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getPlanning", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetPlanning")
    @ResponseWrapper(localName = "getPlanningResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.GetPlanningResponse")
    @WebResult(name = "planning", targetNamespace = "")
    public fr.polytech.polydiploma.remote.stubs.Planning getPlanning();

    @WebMethod
    @RequestWrapper(localName = "setDateOfCerenomy", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.SetDateOfCerenomy")
    @ResponseWrapper(localName = "setDateOfCerenomyResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", className = "fr.polytech.polydiploma.remote.stubs.SetDateOfCerenomyResponse")
    public void setDateOfCerenomy(
        @WebParam(name = "date", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Date date,
        @WebParam(name = "timeslot", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Timeslot timeslot
    );
}
