package fr.polytech.polydiploma.remote.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-05-01T20:24:41.699+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "OrganisationWebServiceImplService", 
                  wsdlLocation = "file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientOrganisation/src/main/resources/OrganisationWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation") 
public class OrganisationWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", "OrganisationWebServiceImplService");
    public final static QName OrganisationWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation", "OrganisationWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientOrganisation/src/main/resources/OrganisationWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrganisationWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientOrganisation/src/main/resources/OrganisationWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrganisationWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrganisationWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganisationWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrganisationWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrganisationWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrganisationWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrganisationWebService
     */
    @WebEndpoint(name = "OrganisationWebServiceImplPort")
    public OrganisationWebService getOrganisationWebServiceImplPort() {
        return super.getPort(OrganisationWebServiceImplPort, OrganisationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrganisationWebService
     */
    @WebEndpoint(name = "OrganisationWebServiceImplPort")
    public OrganisationWebService getOrganisationWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(OrganisationWebServiceImplPort, OrganisationWebService.class, features);
    }

}
