
package fr.polytech.polydiploma.remote.stubs;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-05-03T20:40:39.812+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "SpeakerAlreadyExistException", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/organisation")
public class SpeakerAlreadyExistException_Exception extends Exception {
    
    private fr.polytech.polydiploma.remote.stubs.SpeakerAlreadyExistException speakerAlreadyExistException;

    public SpeakerAlreadyExistException_Exception() {
        super();
    }
    
    public SpeakerAlreadyExistException_Exception(String message) {
        super(message);
    }
    
    public SpeakerAlreadyExistException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SpeakerAlreadyExistException_Exception(String message, fr.polytech.polydiploma.remote.stubs.SpeakerAlreadyExistException speakerAlreadyExistException) {
        super(message);
        this.speakerAlreadyExistException = speakerAlreadyExistException;
    }

    public SpeakerAlreadyExistException_Exception(String message, fr.polytech.polydiploma.remote.stubs.SpeakerAlreadyExistException speakerAlreadyExistException, Throwable cause) {
        super(message, cause);
        this.speakerAlreadyExistException = speakerAlreadyExistException;
    }

    public fr.polytech.polydiploma.remote.stubs.SpeakerAlreadyExistException getFaultInfo() {
        return this.speakerAlreadyExistException;
    }
}
